/**************************************************************************************
* 因为emWin显示只支持UTF-8编码格式的中文，如果希望直接显示在Keil直接输入的中文，      *
*            比如使用：GUI_DispStringHCenterAt("流水灯",110,120);                     *
* 该文件必须以UTF-8编码格式，不然中文无法正常显示。                                   *
*                                                                                     *
* 如果只是个别例程出现中文显示乱码（如果所有例程都无法显示中文可能是字库问题），      *
* 把对应的例程文件(比如LEDapp.c)用电脑的记事本软件打开，然后选择另存为，在弹出对      *
* 话框中“保存(S)"按钮的左边有个"编码(E)"选项，选择"UTF-8",然后同样保存为同名称的      *
* C语言文件(覆盖原来文件)，再编译。                                                   *
*                                                                                     *
* 如果编译工程时出现下面类似错误也是该文件编码格式问题,必须把文件保存为UTF-8格式      *
* 再编译                                                                              *
* ..\..\User\app\LEDapp.c(275): error:  #8: missing closing quote                     *
*        GUI_DispStringHCenterAt("娴?姘?鐏?",110,120);                                *
* ..\..\User\app\LEDapp.c(276): error:  #165: too few arguments in function call      *
*        GUI_DispStringHCenterAt("瑙?鎽?鍋?宸?澶?鎵?闇€瑕?瑙?鎽?鏍?鍑?",110,215);     *
* ..\..\User\app\LEDapp.c(276): error:  #18: expected a ")"                           *
*        GUI_DispStringHCenterAt("瑙?鎽?鍋?宸?澶?鎵?闇€瑕?瑙?鎽?鏍?鍑?",110,215);     *
*                                                                                     *
* 修改文件后编译就出错这是Keil5软件问题(Keil4没这问题)，推荐使用其他程序编辑工具，    *
* 只用Keil5完成编译和下载工作。                                                       *
***************************************************************************************
*                      实验平台: 野火STM32 ISO 开发板                                 *
*                      论    坛: http://www.chuxue123.com                             *
*                      淘    宝: http://firestm32.taobao.com                          *
*                      邮    箱: wildfireteam@163.com                                 *
***************************************************************************************
*/
/**************************************************************************************
*                                                                                     *
*                SEGGER Microcontroller GmbH & Co. KG                                 *
*        Solutions for real time microcontroller applications                         *
*                                                                                     *
***************************************************************************************
*                                                                                     *
* C-file generated by:                                                                *
*                                                                                     *
*        GUI_Builder for emWin version 5.22                                           *
*        Compiled Jul  4 2013, 15:16:01                                               *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG                                *
*                                                                                     *
***************************************************************************************
*                                                                                     *
*        Internet: www.segger.com  Support: support@segger.com                        *
*                                                                                     *
***************************************************************************************
*/

// USER START (Optionally insert additional includes)
#include  "includes.h"
#include  "app.h"
#include  "..\User\bsp\lcd\bsp_ili9341_lcd.h"
#include  "..\User\bsp\ESP8266\bsp_esp8266.h"
#include ".\bmp\bsp_bmp.h"

// USER END

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern uint8_t Ov7725_vsync;
extern OV7725_MODE_PARAM cam_mode; // 选择OV7725的采样模式

extern FATFS* fs;													/* FatFs文件系统对象 */
extern FRESULT result;                /* 文件系统操作结果 */
// USER END

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/* 本回调函数负责光照模式的改变以及特殊模式的切换*/
void cbCameraWin(WM_MESSAGE * pMsg)
{
	switch (pMsg->MsgId) 
	{
	  case WM_DELETE:
			OS_INFO("Cameraapp delete\n");
			DisableCamera();
			Flag_ICON102=0;
			UserApp_Flag = 0;		
			ILI9341_GramScan(1);
			tpad_flag=0;
			break;
		case WM_PAINT:
			GUI_SetBkColor(GUI_WHITE);
			GUI_Clear();
			GUI_DispStringHCenterAt("camera init fail",110,110);
			break;
	}
}
/*********************************************************************
*
*       CreateCamera
*/
void FUN_ICON102Clicked(void)
{
	WM_HWIN hWin;
	OS_ERR     err;
	// uint32_t i=0;
	// uint16_t Camera_Data;
	uint8_t count=0;
	
	ESP8266_stop();
	
	OS_INFO("Cameraapp create\n");
	hWin=WM_CreateWindowAsChild(0,0,240,320,WM_HBKWIN,WM_CF_SHOW,cbCameraWin,0);
	GUI_Delay(100);
	
	/* ov7725 gpio 初始化 */
	Ov7725_GPIO_Config();
	/* ov7725 寄存器配置初始化 */
	while(count<10)
	{		
		if(Ov7725_Init())break;
		bsp_DelayUS(1000);
		count++;
	}
	while(count==10)
	{		
		WM_InvalidateWindow(hWin);
		GUI_ExecCreatedDialog(MESSAGEBOX_Create("\r\n The Camera drive cannot work! \r\n","error",GUI_MESSAGEBOX_CF_MODAL));
		while(1)
		{
			WM_DeleteWindow(hWin);
			if(!Flag_ICON102)return;
			GUI_Delay(10);
		}
	}
	/*按键初始化*/
	Key1_GPIO_Config();
	
	/*LED提示灯初始化*/
	LED_GPIO_Config();
	
	/*挂载SD卡的文件系统*/
	printf("0-0\n");
	result=f_mount(fs,"0:",1);	
	printf("0-1\n");	
	
	if(result != FR_OK)
	{
		printf("\r\nSD-CARD FILE SYSTEM ERROR!\r\n");
	}
	
	
	/* ov7725 场信号线初始化 */
	VSYNC_Init();
	Ov7725_vsync = 0;
	ILI9341_GramScan(2);
	bsp_DelayUS(10);
	
	/*设置OV7725的采样模式*/
	OV7725_Special_Effect(cam_mode.effect);
	/*亮度模式*/
	OV7725_Light_Mode(cam_mode.light_mode);
	/*饱和度*/
	OV7725_Color_Saturation(cam_mode.saturation);
	/*亮度*/
	OV7725_Brightness(cam_mode.brightness);
	/*对比度*/
	OV7725_Contrast(cam_mode.contrast);
	/*模式调节*/
	OV7725_Special_Effect(cam_mode.effect);
	
	/*采样大小设置*/
	OV7725_Window_Set(cam_mode.cam_sx,
														cam_mode.cam_sy,
														cam_mode.cam_width,
														cam_mode.cam_height,
														cam_mode.QVGA_VGA);
	
	
	
	/* 设置液晶的扫描方式（注意横竖的扫描方式参数不同）*/
	ILI9341_GramScan( cam_mode.lcd_scan );
	
	while(1)
	{
		printf("1");
		if( Ov7725_vsync == 2 )
		{			
			printf("2");
			OSSchedLock(&err);			
			FIFO_PREPARE;  			/*FIFO准备*/
			/*采集并显示*/
			
			ImagDisp(cam_mode.lcd_sx,
								cam_mode.lcd_sy,
								cam_mode.cam_width,
								cam_mode.cam_height);	
			
			OSSchedUnlock(&err);
			Ov7725_vsync = 0;						
		}
		
		/*拍照*/
		/*Key1拍照模式*/
	  if( Key_Scan(KEY1_PORT,KEY1_PIN) == KEY_ON  )
		{		
			static uint8_t name_count = 0;
			char name[40];
			
			
			name_count++; 
			sprintf(name,"0:photo_%d.bmp",name_count);

			LED_BLUE;
			printf("\r\nCapturing the picture...");
		
			ILI9341_GramScan ( cam_mode.lcd_scan );			
			
			if(Screen_Shot(0,0,240,320,name) == 0)
			{
				printf("\r\nSave successfully!");
				LED_GREEN;
			}
			else
			{
				printf("\r\n save failed!");
				LED_RED;
			}
		}
		
		/*触屏拍照模式*/
		
		
		if(tpad_flag)WM_DeleteWindow(hWin);
		GUI_Delay(1);//WM_Exec();//
	}
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/